spring:
  application:
    name: dama-italiana-client
  main:
    web-application-type: none
    banner-mode: "off"

dama:
  client:
    saves-dir: ${user.home}/.dama-italiana/saves
    config-file: ${user.home}/.dama-italiana/config.json

logging:
  level:
    root: INFO
    com.damaitaliana: INFO
